version: 0.2

env:
  #variables:
     # key: "value"
     # key: "value"
  parameter-store:
      DOCKER_REGISTRY_USERNAME: /myapp/docker_credentials/username
      DOCKER_REGISTRY_PASSWORD: /myapp/docker_credentials/password
      DOCKER_REGISTRY_URL: /myapp/docker_credentials/url
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    runtime-versions:
      python: 3.11
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - pip install -r day-14/simple-python-app/requirements.txt
      # - command
  build:
    commands:
      - cd day-14/simple-python-app
      - echo "building docker image"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple_python_flask_app:latest" .
      - docker push $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple_python_flask_app:latest
      # - command
  post_build:
    commands:
      - echo "Build is successful"
      # - command
